package br.com.odontologic.util;

import java.util.ArrayList;
import java.util.List;

public class RetornaFraseCaminhao {
	
	
	
	public static String fraseCaminhao(){
		List<String> frases = new ArrayList<String>();
		frases.add("20 Buscar 100 demora 60 aqui e vamos embora.");
		frases.add("3 eixos envenenados e 1 machão invocado.");
		frases.add("6 pneus cheios e 1 coração vazio. ");
		frases.add("70 me passar, passe 100 atrapalhar.");
		frases.add("80ção 20buscar 100você, não sei viver!");
		frases.add("99% da beleza feminina sai com água e sabão.");
		frases.add("Adoro as rosas, mas prefiro as trepadeiras... ");
		frases.add("A fé remove montanhas, mas eu prefiro dinamite.");
		frases.add("A fome é o melhor tempero.");
		frases.add("A fortuna faz amigos. A desgraça prova se eles existem de fato.");
		frases.add("A gente se encontra um dia, quando eu voltar.");
		frases.add("Agora vou votar nas putas ... cansei de votar nos filhos delas.");
		frases.add("A mata é virgem porque o vento é fresco. ");
		frases.add("A melhor maneira de se lembrar do aniversario da mulher é esquecê-lo uma vez. ");
		frases.add("A melhor vacina contra a AIDS é a comida caseira.");
		frases.add("Amigos vem e se vão, inimigos se acumulam.");
		frases.add("Antes dava um boi para não entrar numa briga, hoje brigo por um bife!");
		frases.add("A primeira ilusão do homem começa na chupeta. ");
		frases.add("As mulheres perdidas são as mais procuradas.");
		frases.add("A vida é dura para quem é mole. ");
		frases.add("Bebo para esquecer, só não lembro do que! ");
		frases.add("Beijo é igual ferro elétrico, liga em cima e esquenta embaixo.");
		frases.add("Caminhoneiro que tem mulher feia, viaja sempre tranquilo.");
		frases.add("Casamento não é bom e isto é fato verdadeiro, pois o diabo não se casou e Jesus morreu solteiro.");
		frases.add("Casar é trocar a admiração de várias mulheres, pela crítica de uma só!!!");
		frases.add("Chifre é igual dente, só dói enquanto tá nascendo. ");
		frases.add("Chifre não existe ... isto é coisa que puseram na sua cabeça.");
		frases.add("Coceira de rico é alergia, de pobre é sarna! ");
		frases.add("Coceira na mão de pobre é sarna, na mão de rico é dinheiro.");
		frases.add("Começei a beber por causa de uma mulher, e nunca tive a oportunidade de agradecê-la.");
		frases.add("Como estou dirigindo? Mal? F... -se, o caminhão é meu!");
		frases.add("Deus abençoe as mulheres bonitas, e as feias se sobrar tempo. ");
		frases.add("Deus criou o carro para o rico andar e o Diabo criou o caminhão para o pobre trabalhar.");
		frases.add("Deus pôde fazer o mundo em 6 dias porque não tinha ninguém perguntando quando ia ficar pronto. ");
		frases.add("Dinheiro não traz felicidade ...  então me dê o seu e seja feliz.");
		frases.add("Dinheiro não traz felicidade ...  manda buscar.");
		frases.add("Dirijo com cuidado para não deixar chorando quem me espera sorrindo.");
		frases.add("Dirijo devagar, tenho pressa de chegar!");
		frases.add("Dizem que dinheiro é coisa do diabo; mas se quiser ver o diabo, ande sem dinheiro.");
		frases.add("Duas coisas que eu gosto: cerveja gelada e mulher quente. ");
		frases.add("Durmo com Mercedez B. e sonho com Maria.");
		frases.add("Em casa, de dia ela manda, à noite eu obedeço. ");
		frases.add("Em casa, Maria reza. Na estrada, Mercedes Benze.");
		frases.add("Em casa minha mulher é o governo; minha sogra, o ministro da defesa e eu o ministro da despesa!");
		frases.add("Em terra de cego quem tem um olho é caolho.");
		frases.add("Enquanto não encontro a mulher certa...me divirto com as erradas.");
		frases.add("Escola enriquece, veja o dono dela. ");
		frases.add("Este é um Ford, mas se bater Ford tudo!");
		frases.add("Estepe e mulher é sempre bom ter de reserva. ");
		frases.add("Este veículo é rastreado por Deus.");
		frases.add("Estou indo, mas VOLVO rtar logo.");
		frases.add("Estrada e mulher sem curvas só dão sono.");
		frases.add("Estudar é a luz da vida, pare de estudar! economize energia!");
		frases.add("Eu sempre me importei com a beleza interior das mulheres. Uma vez dentro ... Beleza!");
		frases.add("Eu sou imortal, pois não tenho onde cair morto!");
		frases.add("Eu sou U 1000 D.");
		frases.add("Farol alto na cara é como mulher gritando no ouvido. ");
		frases.add("Felicidade é uma viagem, e não um destino. ");
		frases.add("Feliz foi Adão, que não teve sogra nem caminhão.");
		frases.add("Filho de rico é Playboy, de pobre é office-boy. ");
		frases.add("Filho é igual peido: você só agüenta o seu. ");
		frases.add("Foi nas curvas da vida, que eu capotei meu coração.");
		frases.add("Galinha velha dá bom caldo, mas são as frangas novas que fazem o Galo cantar! ");
		frases.add("Guarde seu silêncio, para que não fique escravo de suas palavras.");
		frases.add("Herrar é umano! ");
		frases.add("Hoje tem que ser só uma rapidinha porque o frete é perecível. ");
		frases.add("Homem é como caminhão basculante: quando velho, não levanta mais ");
		frases.add("Homem é como lata: uma chuta e a outra cata!");
		frases.add("Já que a primeira impressão é a que fica, use uma impressora à laser.");
		frases.add("Já que cada vez mais as mulheres estão indo buscar seus direitos, será que na volta poderiam trazer uma cerveja?");
		frases.add("Jesus é o caminhão que nos leva para o depósito de Deus. ");
		frases.add("Jovem não dorme, dá um tempo. ");
		frases.add("Lenha verde e mulher véia chora, mas pega fogo. ");
		frases.add("Levo-ti no coração para amenizar minha solidão.");
		frases.add("Líder é alguém que você decide seguir até um lugar aonde não iria sozinho.");
		frases.add("Língua afiada separa bons amigos. ");
		frases.add("Lutar sempre, Vencer às vezes, Desistir jamais.");
		frases.add("Macho que é macho não chupa mel, masca abelha. ");
		frases.add("Malandro é o sapo que casa e leva a esposa prá morar no brejo.");
		frases.add("Meus faróis iluminam a estrada e Deus ilumina meu caminho.");
		frases.add("Macho que é macho não engole sapo, come perereca!");
		frases.add("Mais perigoso que cavalo na estrada é um burro no volante.");
		frases.add("Mais vale chegar atrasado neste mundo, do que adiantado no outro.");
		frases.add("Mais virgindades já se perderam pela curiosidade do que pelo amor.");
		frases.add("Marido de mulher feia sempre acorda assustado. ");
		frases.add("Marido de mulher feia tem raiva de feriado. ");
		frases.add("Meu Computador não fala COM PUTA. ");
		frases.add("Meu pensamento continua onde a minissaia termina. ");
		frases.add("Meu pensamento está acima dos seus joelhos.");
		frases.add("Minha sogra caiu do céu... A vassoura dela quebrou. ");
		frases.add("Minha vida é uma rede que o destino balança!");
		frases.add("Minha vida é um litro aberto.");
		frases.add("Muitos me perseguem, poucos me alcançam. ");
		frases.add("Muitos me seguem, mas só um me acompanha!");
		frases.add("Mulher bonita e dinheiro só vejo na mão dos outros.");
		frases.add("Mulher bonita e parafuso, comigo é no arrocho. ");
		frases.add("Mulher de amigo meu é igual árvore, só dá galho. ");
		frases.add("Mulher de amigo meu é que nem cebola: Eu como chorando. ");
		frases.add("Mulher de amigo meu pra mim é ótimo. ");
		frases.add("Mulher deixa o rico sem dinheiro e o pobre sem vergonha. ");
		frases.add("Mulher de mini-saia é o mesmo que cerca de arame farpado, cerca a propriedade mas não tapa a visão.");
		frases.add("Mulher desquitada e cana de engenho só deixam bagaço. ");
		frases.add("Mulher é como abelha: ou dá mel ou ferroada. ");
		frases.add("Mulher é como horóscopo: nunca dá certo, mas sempre se dá uma olhadinha.");
		frases.add("Mulher é como lona de freio: só é boa encostada. ");
		frases.add("Mulher é como relógio: deu o primeiro defeito, nunca mais anda direito!");
		frases.add("Mulher é como remédio: agita-se antes de usar. ");
		frases.add("Mulher é como retrato, só se revela no escuro.");
		frases.add("Mulher feia é como pantufa... Dentro de casa, até que é gostosinha mas na rua...dá uma vergonha!!!");
		frases.add("Mulher é como toalha; quanto mais enxuta, melhor ");
		frases.add("Mulher e estrada cheia de curvas, é um perigo. ");
		frases.add("Mulher e fotografia só se revelam no escuro. ");
		frases.add("Mulher é igual alça de caixão: quando um larga vem outro e põe a mão.");
		frases.add("Mulher é igual circo: é debaixo do pano que está o espetáculo.");
		frases.add("Mulher é igual pipoca, quando dá uns pulinhos cai logo na boca do povo. ");
		frases.add("Mulher é igual relógio: depois do primeiro defeito, nunca mais anda direito. ");
		frases.add("Mulher e índio quando se pintam, é que vão prá guerra.");
		frases.add("Mulher feia e cheque sem fundo, protesto.");
		frases.add("Mulher feia é igual a ventania, só quebra galho. ");
		frases.add("Mulher feia é igual jiló. Pouca gente come. ");
		frases.add("Mulher feia e morcego só saem à noite. ");
		frases.add("Mulher feia e jumento só quem procura é o dono. ");
		frases.add("Mulher feia vale por duas porque o marido sempre tem outra. ");
		frases.add("Mulher gata, gostosa, gente fina e fiel é igual a nota de R$ 30,00. Eu nunca vi...!!!");
		frases.add("Mulher no volante, perigo constante.");
		frases.add("Na cabina cabem muitas; no coração só uma. ");
		frases.add("Na calada da noite a população se multiplica. ");
		frases.add("Na estrada da vida não tem acostamento.");
		frases.add("Na subida você me aperta, na descida nois se acerta.");
		frases.add("Nas curvas de teu corpo capotei meu coração. ");
		frases.add("Não aponte as falhas alheias com o dedo sujo. ");
		frases.add("Não bebo água, os peixes transam nela.");
		frases.add("Não buzine! Acorde mais cedo.");
		frases.add("Não digue adeus. Digue até breve.");
		frases.add("Não dirija mais rápido que seu anjo possa acompanhar.");
		frases.add("Não é pressa, é saudade. ");
		frases.add("Não faça de seu namorado um tarado: a vítima pode ser você. ");
		frases.add("Não faça na vida pública aquilo que você faz na privada.");
		frases.add("Não fale dos seus grandes problemas para Deus, fale para os problemas do seu grande Deus.");
		frases.add("Não falo com a minha esposa há mais de um ano!  Não quero interrompê-la...");
		frases.add("Não há melhor momento do que hoje, para deixar para amanhã o que você não vai fazer nunca.");
		frases.add("Não jogue espinhos na estrada...na volta você pode estar a pé.");
		frases.add("Não leve a vida tão a sério : Você não vai sair vivo dela, mesmo !");
		frases.add("Não mando a minha sogra para o inferno porque tenho pena do diabo. ");
		frases.add("Não me inveje, trabalhe.");
		frases.add("Não me siga, posso estar perdido.");
		frases.add("Não passe tempo demais pensando em sua vida. Você não deve perder tempo com bobagens!");
		frases.add("Não perca o bom humor, pois quem achar não devolverá.");
		frases.add("Não se esqueça, Jesus te ama...mas eu não!");
		frases.add("Não se pode fazer um omelete, sem quebrar os ovos! ");
		frases.add("Não sou baton, mas vivo nas bocas.");
		frases.add("Não sou detetive mas só ando na pista. ");
		frases.add("Não sou dono do mundo, mas sou filho dele.");
		frases.add("Não sou notícia ruim mas ando muito e depressa.");
		frases.add("Não sou orquestra, mas vivo no conserto.");
		frases.add("Não sou rei, mas gosto da coroa. ");
		frases.add("Não sou sapo, mas gosto de uma perereca. ");
		frases.add("Não sou Silvio Santos, mas vivo do Baú!");
		frases.add("Não tenho tudo na vida, mas amo tudo que tenho.");
		frases.add("Não tenho tudo que amo, mas.... DANE-SE! ");
		frases.add("Não tenho vícios. Só bebo e fumo quando jogo.");
		frases.add("Não ultrapasse em local proibido, para não deixar mais uma viúva a procura de marido.");
		frases.add("Não vou bem como quero nem mal como pensam.");
		frases.add("Nasci careca, pelado e sem dente. O que vier é lucro!");
		frases.add("Na subida, paciência; na descida, dá licença.");
		frases.add("Navio imita tubarão; avião imita gavião; só meu caminhão não tem imitação.");
		frases.add("Nem todos os homens são idiotas, alguns são solteiros.");
		frases.add("No baralho da vida encontrei apenas uma dama.");
		frases.add("No Havaí, todas as sandálias são havaianas.");
		frases.add("Nóis capota mas não breka.");
		frases.add("Nosso amor virou cinzas, depois de saber que seu passado era fogo.");
		frases.add("Nosso amor virou cinzas porque nosso passado foi fogo.");
		frases.add("No teatro do poder, todos são formados em artes cínicas!");
		frases.add("Nunca desista de seu sonho!...você sempre vai encontrá-lo em alguma padaria!");
		frases.add("Nunca é tarde para ser feliz. ");
		frases.add("Nunca tive problemas com drogas ... só com a polícia.");
		frases.add("O amor é cego, mas o casamento abre os olhos. ");
		frases.add("O amor é livre; o sexo é pago. ");
		frases.add("O beijo é como cigarro: não sustenta, mas vicia. ");
		frases.add("O bom não é ser importante: o importante é ser bom!");
		frases.add("O cal é virgem porque o cimento é fresco.");
		frases.add("O casamento é a sepultura do amor! ");
		frases.add("O chifre é como consórcio, quando você menos espera, é contemplado.");
		frases.add("O erro da vida não tem borracha que apague!");
		frases.add("O futuro depende dos seus sonhos! Por isto não perca tempo, vá para casa dormir.");
		frases.add("O importante é o principal porque o resto é secundário!");
		frases.add("O K7 é virgem porque o som é estéril. ");
		frases.add("Olhe para a mulher do próximo, mas conserve a sua à direita.");
		frases.add("O mal da vida é ser a pessoa certa na hora errada.");
		frases.add("O mundo abre as portas para aqueles que sabem onde querem ir.");
		frases.add("O mundo é chato pra quem é quadrado.");
		frases.add("Ontem éramos três: eu, você e o amor. Hoje somos apenas dois: eu e a solidão. ");
		frases.add("O pessimista considera o sol um fazedor de sombras. ");
		frases.add("O prazer dá o que a sabedoria promete. ");
		frases.add("O que conta não é beleza interior e sim ter uma beleza de conta no exterior.");
		frases.add("O sol nasce para todos; a sombra para quem merece.");
		frases.add("Os últimos serão os desclassificados!");
		frases.add("Os últimos serão os primeiros e os do meio, sempre serão os do meio. ");
		frases.add("O trabalho foi inventado por quem não tinha o que fazer !");
		frases.add("O verdadeiro homem não é aquele que conquista várias mulheres, mas sim aquele que conquista a mesma várias vezes.");
		frases.add("Papel que une dois corpos não prende um coração!");
		frases.add("Para comprar caminhão e usar sutiã precisa ter peito. ");
		frases.add("Para evitar filhos, transe com a cunhada só nascem sobrinhos.");
		frases.add("Para que levar a vida a sério, se nós nascemos de uma gozada?");
		frases.add("Para quem está afundando, jacaré é tronco! ");
		frases.add("Para quem está perdido, qualquer atalho serve! ");
		frases.add("Para que um olho não invejasse o outro, Deus colocou o nariz no meio!! ");
		frases.add("Perigo não é um cavalo na pista, é um burro na direção. ");
		frases.add("Pior do que nunca achar a pessoa certa é viver prá sempre com a errada!");
		frases.add("Pobre é como cachimbo: só leva fumo!");
		frases.add("Pobre é igual pneu velho, só anda na lona! ");
		frases.add("Pobre é igual pneu, quando mais trabalha mais liso fica. ");
		frases.add("Pobre é que nem disco de embreagem, quanto mais trabalha mais liso fica.");
		frases.add("Pobre é que nem lombriga: quando sai da merda, morre...");
		frases.add("Pobre parado é suspeito, correndo é ladrão! ");
		frases.add("Pobre só enche a barriga quando morre afogado. ");
		frases.add("Pobre só vai para frente quando tropeça. ");
		frases.add("Político bom é político desempregado.");
		frases.add("Por falta de roupa nova, passei o ferro na velha.");
		frases.add("Por que ficar de braços cruzados se o maior homem morreu de braços abertos?");
		frases.add("Prefiro chegar tarde em casa, do que cedo no cemitério.");
		frases.add("Prefiro ser um bêbado conhecido do que um alcoólatra anônimo. ");
		frases.add("Prefiro ser um pai quadrado do que ver minha filha redonda! ");
		frases.add("Prefiro perder 1 minuto na vida, do que a vida em 1 minuto.");
		frases.add("Preguiça é o habito de descansar antes de estar cansado.");
		frases.add("Preguiçoso é o dono da sauna, que vive do suor dos outros.");
		frases.add("Quando a galinha é boa... o pinto não falha.");
		frases.add("Quando o nosso amor virar cinzas, lembre-se que eu sempre mandei brasa.");
		frases.add("Quando um homem abre a porta do carro para a mulher, é porque ainda não comeu. ");
		frases.add("Quanto mais conheço os homens mais admiro os cachorros.");
		frases.add("Que Deus te dê em dobro, tudo que me desejas. ");
		frases.add("Quem ama a rosa suporta os espinhos. ");
		frases.add("Quem cedo madruga, fica com sono o dia inteiro.");
		frases.add("Quem corre cansa, quem anda alcança. ");
		frases.add("Quem dá aos pobres empresta a Deus e quem empresta ao Governo dá adeus. ");
		frases.add("Quem dá aos pobres, tem que pagar o Motel!");
		frases.add("Quem fala de mim tem inveja ou paixão. ");
		frases.add("Quem fala o que quer, escuta o que não quer.");
		frases.add("Quem gosta de motorzinho é dentista! ");
		frases.add("Quem gosta de mulher feia é salão de beleza. ");
		frases.add("Quem inventou a distância não conhecia a saudade.");
		frases.add("Quem ri por último é porque não entendeu a piada. ");
		frases.add("Quem se curva aos opressores, mostra a bunda aos oprimidos! ");
		frases.add("Quem tem olho gordo, usa colírio diet.");
		frases.add("Quem vive de rendas é vendedor de sutiã. ");
		frases.add("Quer saber quanto vale sua mulher? Peça o divórcio.");
		frases.add("Respeite a mulher do próximo, principalmente se o próximo estiver muito próximo.");
		frases.add("Rico pega o carro e sai, pobre sai e o carro pega.");
		frases.add("Rico quando corre está fazendo cooper, pobre quando corre está fugindo da polícia.");
		frases.add("Rico tem veia poética; pobre tem varizes.");
		frases.add("Roubar dos ricos e dá aos pobres. Além de ladrão é gay.");
		frases.add("São nas derrotas que ganho força para as vitórias.");
		frases.add("Se a gula é um pecado, o inferno deve ser ótimo pra fazer churrasco.");
		frases.add("Se a morte for um descanso, prefiro viver cansado. ");
		frases.add("Se andar fosse bom, o carteiro seria imortal. ");
		frases.add("Se a sua estrela não brilha, não ofusque a minha.");
		frases.add("Se barba fosse respeito, bode não tinha chifre.");
		frases.add("Se casamento fosse bom não precisaria de testemunhas. ");
		frases.add("Se casamento fosse estrada, eu só andava no acostamento. ");
		frases.add("Se CHEFE fosse arquivo, a extensão seria '.fdp'");
		frases.add("Se chiar resolvesse, sal de frutas não morria afogado.");
		frases.add("Se chover mulher, quero goteira na minha cama. ");
		frases.add("Se correr o guarda pega, se parar o banco toma.");
		frases.add("Se Deus é a estrada, Edir Macedo é o pedágio.");
		frases.add("Se Deus é por nós, quem será contra.");
		frases.add("Se dinheiro falasse... o meu diria tchau!");
		frases.add("Se é para morrer de batida, prefiro de limão.");
		frases.add("Se ferradura desse sorte, burro não puxava carroça. ");
		frases.add("Segredo entre três, só matando dois. ");
		frases.add("Seja dono de sua boca para não ser escravo de suas palavras! ");
		frases.add("Seja legal com seus filhos. São eles que vão escolher seu asilo.");
		frases.add("Seja otimista : pense que por maior que seja o buraco em que você se encontra, por enquanto ainda não há terra em cima.");
		frases.add("Seja paciente na estrada para não ser paciente no hospital.");
		frases.add("Se me ver abraçado com mulher feia, pode separar que é briga.");
		frases.add("Se não gosta do jeito que dirijo, saia da calçada. ");
		frases.add("Se o amor é cego, o negócio é apalpar.");
		frases.add("Se o amor matasse, eu já estaria morto de tanto amar você.");
		frases.add("Se o Bach é bom, O Chopin é Brahms !");
		frases.add("Se o homem fala de sexo com mulher é assédio sexual, se mulher fala de sexo com homem é R$ 1,99 por minuto.");
		frases.add("Se pinga fosse fortificante o brasileiro seria um gigante. ");
		frases.add("Se queres achar amizade, doçura e poesia em qualquer parte, leva-as contigo.");
		frases.add("Seria pior, se pior estivesse. ");
		frases.add("Se ruga fosse sinal de velhice, meu saco tinha 500 anos.");
		frases.add("Se sua mulher pedir mais liberdade, compre uma corda mais comprida.");
		frases.add("Se tamanho fosse documento o elefante era dono do circo. ");
		frases.add("Se teta fosse buzina, ninguém dormia a noite.");
		frases.add("Ser bissexual dobra suas chances para um encontro no fim de semana.");
		frases.add("Se você estiver sem calcinha, dê uma risadinha.");
		frases.add("Sexo demais prejudica a memória e outra coisa que não me lembro agora.");
		frases.add("Sexo grátis, amor à combinar.");
		frases.add("Só dou carona para quem me dá.");
		frases.add("Só o Ctrl+S salva.");
		frases.add("Sogra e onça pintada muita gente defende, mas ninguém quer levar para casa.");
		frases.add("Sogra devia ser que nem batata, já nascer debaixo da terra.");
		frases.add("Sogro rico e porco gordo só dão lucro depois de mortos.");
		frases.add("Sorria... sua mulher me ama.");
		frases.add("Sou a favor da ecologia... Mas adoro afogar o ganso.");
		frases.add("Sou feio, mas sou carinhoso. ");
		frases.add("Sou grande porque respeito os pequenos.");
		frases.add("Suba na vida mas não faça ninguém de escada! ");
		frases.add("Tá ruim, mas tá bom.");
		frases.add("Te amo mais que ontem e menos que amanhã.");
		frases.add("Televisão de pobre é buraco de fechadura. ");
		frases.add("Todos os cogumelos são comestíveis. Alguns só uma vez.");
		frases.add("Tudo na vida é passageiro. Exceto o motorista e o cobrador.");
		frases.add("Tudo na vida muda, até a surda muda. ");
		frases.add("Tudo que é bom na vida ou faz mal ou é pecado. ");
		frases.add("Uma das funções do Espírito Santo é aumentar a distância entre o Rio e a Bahia.");
		frases.add("Um casamento vai para o brejo quando você começa a engolir tantos sapos que não sobra mais tempo para comer a perereca!");
		frases.add("Um dia ela me disse..Ou eu,ou o caminhão Sinto saudades DELA...");
		frases.add("Vai-se o vento, leva-se o tempo.");
		frases.add("Veja os teus erros, depois corrija os meus. ");
		frases.add("Velocidade controlada pelos buracos da estrada. ");
		frases.add("Viajo no mundo, e passeio em casa!");
		frases.add("Viajo porque gosto, volto porque te amo.");
		frases.add("Vitamina de chofer é poeira. ");
		frases.add("Viver é desenhar sem borracha.");
		frases.add("Você já cheirou Coca? ... Tem o mesmo cheiro da Pepsi!");
		frases.add("Você mora no meu coração e não paga aluguel.");
		frases.add("Você prefere duas mulheres ou uma mulher e 1/4? ");
		frases.add("Vou rezar 1/3 para arranjar um 1/2 para te levar para 1/4. ");

		int randon = (int) Math.round(Math.random()*frases.size());
		
		return frases.get(randon);
	};
	
	
	
}
